import type { Metadata } from 'next';
import Link from 'next/link';
import { HeroDataSculpture } from '@/components/hero-data-sculpture';
import { ValueExplorer } from '@/components/value-explorer';
import { ProjectCard } from '@/components/project-card';
import { Icon } from '@/components/icons';
import { getPortfolioContent } from '@/lib/cms';

export const metadata: Metadata = {
  title: 'Ahmed Aziz Mhiri | Marketing Data Analysis, BI and Automation',
  description: 'Ahmed Aziz Mhiri works across data, automation, marketing and business operations to make processes clearer, customer journeys smoother and commercial decisions better informed.',
  alternates: { canonical: '/' },
  openGraph: { title: 'Ahmed Aziz Mhiri | Marketing Data Analysis, BI and Automation', description: 'Data, automation, marketing and business operations for clearer processes and better-informed commercial decisions.' },
};

export default async function HomePage() {
  const { profile, projects, experiences, skillClusters, education, certifications, valueCards } = await getPortfolioContent();
  return <>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="pulse-dot" /> Marketing data analysis, BI and automation</p><h1>{profile.homepageTitle}</h1><p className="hero-tagline">{profile.tagline}</p><p className="hero-summary">{profile.summary}</p><p className="availability"><span>Europe-focused roles</span>{profile.availability}</p><div className="hero-actions"><Link className="button button-primary" href="/projects">View Selected Projects <Icon name="arrow" /></Link><Link className="button button-secondary" href="/resume"><Icon name="download" /> Download CV</Link><a className="text-link hero-link" href={profile.linkedIn} target="_blank" rel="noreferrer">Connect on LinkedIn <Icon name="external" /></a></div></div><div className="hero-visual"><HeroDataSculpture /><div className="portrait-wrap"><img src={profile.portraitUrl} alt="Portrait of Ahmed Aziz Mhiri" width="1003" height="1003" fetchPriority="high" /></div><aside className="glance-card" aria-label="At a glance"><span className="eyebrow">At a glance</span><ul><li>Marketing Data Analyst</li><li>Business Intelligence Analyst</li><li>Revenue Operations Analyst</li><li>Automation and CRM Specialist</li></ul></aside></div></div></section>
    <section className="section section-soft"><div className="shell section-header split-heading"><div><p className="eyebrow">How I contribute</p><h2>Clearer reporting, smoother customer journeys and more reliable workflows.</h2></div><p>Ahmed works on practical analytical and digital problems: organising data, improving customer touchpoints, checking operational details and making business processes easier to review.</p></div><div className="shell"><ValueExplorer cards={valueCards} /></div></section>
    <section className="section"><div className="shell section-header row-header"><div><p className="eyebrow">Selected projects</p><h2>Examples of work across automation, customer journeys and AI-supported learning.</h2></div><Link href="/projects" className="text-link">Explore My Work <Icon name="arrow" /></Link></div><div className="shell project-grid">{projects.map((project) => <ProjectCard project={project} key={project.id || project.slug} />)}</div></section>
    <section className="section timeline-section"><div className="shell section-header split-heading"><div><p className="eyebrow">Experience snapshot</p><h2>Business context first, then the right tools.</h2></div><p>Experience across tourism operations, commercial marketing, hospitality performance analysis and enterprise software.</p></div><div className="shell compact-timeline">{experiences.slice(0, 5).map((item, index) => <article className="timeline-item" key={item.id || item.organisation}><div className="timeline-marker">0{index + 1}</div><div><p className="timeline-date">{item.dates}</p><h3>{item.role}</h3><p className="timeline-org">{item.organisation} - {item.location}</p><p>{item.summary}</p></div></article>)}</div><div className="shell timeline-action"><Link href="/experience" className="button button-secondary">View Full Experience <Icon name="arrow" /></Link></div></section>
    <section className="section section-soft"><div className="shell section-header split-heading"><div><p className="eyebrow">Skills</p><h2>Tools and methods for analytics, automation and digital marketing work.</h2></div><p>Skills used to organise data, improve customer interactions, support reporting and make business processes more repeatable.</p></div><div className="shell skills-grid">{skillClusters.map((cluster, index) => <article className="skill-cluster" key={cluster.id || cluster.title}><span className="cluster-index">0{index + 1}</span><h3>{cluster.title}</h3><div className="skill-tags">{cluster.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
    <section className="section education-section"><div className="shell education-grid"><div><p className="eyebrow">Education and certification</p><h2>Built on business intelligence, extending into data and e-commerce.</h2></div><div className="education-list">{education.map((item) => <article key={item.id || item.title}><h3>{item.title}</h3><p>{item.organisation}</p><span>{item.date}</span>{item.detail && <small>{item.detail}</small>}</article>)}{certifications.map((item) => <article className="cert-card" key={item.id || item.title}><p className="eyebrow">Certification</p><h3>{item.title}{item.issuer ? ` - ${item.issuer}` : ''}</h3>{item.detail && <small>{item.detail}</small>}</article>)}</div></div></section>
    <section className="section contact-cta-section"><div className="shell contact-cta"><p className="eyebrow">Contact</p><h2>Open to recruiters, managers and teams working in analytics, business intelligence, revenue operations, automation and digital marketing.</h2><div className="hero-actions"><a className="button button-primary" href={profile.linkedIn} target="_blank" rel="noreferrer"><Icon name="linkedin" /> Connect on LinkedIn</a><Link className="button button-secondary" href="/contact"><Icon name="mail" /> Get in Touch</Link><Link className="text-link" href="/resume">Download CV <Icon name="download" /></Link></div></div></section>
  </>;
}
