import type { Metadata } from 'next';
import Link from 'next/link';
import { HeroDataSculpture } from '@/components/hero-data-sculpture';
import { ValueExplorer } from '@/components/value-explorer';
import { ProjectCard } from '@/components/project-card';
import { Icon } from '@/components/icons';
import { getPortfolioContent } from '@/lib/cms';

export const metadata: Metadata = {
  title: 'Ahmed Aziz Mhiri | Data-Driven Marketing & Commercial Analytics',
  description: 'Turning data into commercial growth through marketing analytics, commercial analytics, business intelligence, automation and digital customer journeys.',
  alternates: { canonical: '/' },
  openGraph: { title: 'Ahmed Aziz Mhiri | Data-Driven Marketing & Commercial Analytics', description: 'Turning data into commercial growth through analytics, automation and digital customer journeys.' },
};

export default async function HomePage() {
  const { profile, projects, experiences, skillClusters, education, certifications, valueCards } = await getPortfolioContent();
  return <>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="pulse-dot" /> Data, digital growth & operational clarity</p><h1>{profile.homepageTitle}</h1><p className="hero-tagline">{profile.tagline}</p><p className="hero-summary">{profile.summary}</p><p className="availability"><span>Open for Europe</span>{profile.availability}</p><div className="hero-actions"><Link className="button button-primary" href="/projects">Explore Projects <Icon name="arrow" /></Link><Link className="button button-secondary" href="/resume"><Icon name="download" /> Download CV</Link><a className="text-link hero-link" href={profile.linkedIn} target="_blank" rel="noreferrer">Connect on LinkedIn <Icon name="external" /></a></div></div><div className="hero-visual"><HeroDataSculpture /><div className="portrait-wrap"><img src={profile.portraitUrl} alt="Portrait of Ahmed Aziz Mhiri" width="1003" height="1003" fetchPriority="high" /></div><aside className="glance-card" aria-label="At a glance"><span className="eyebrow">At a glance</span><ul><li>Marketing Analytics</li><li>Commercial Analytics</li><li>Business Intelligence</li><li>Automation & Digital Growth</li></ul></aside></div></div></section>
    <section className="section section-soft"><div className="shell section-header split-heading"><div><p className="eyebrow">How I contribute</p><h2>Signals are useful when they change the next decision.</h2></div><p>Focused on the link between business activity, customer touchpoints and commercially useful action.</p></div><div className="shell"><ValueExplorer cards={valueCards} /></div></section>
    <section className="section"><div className="shell section-header row-header"><div><p className="eyebrow">Selected case studies</p><h2>Work across automation, digital journeys and AI-enabled learning.</h2></div><Link href="/projects" className="text-link">All projects <Icon name="arrow" /></Link></div><div className="shell project-grid">{projects.map((project) => <ProjectCard project={project} key={project.id || project.slug} />)}</div></section>
    <section className="section timeline-section"><div className="shell section-header split-heading"><div><p className="eyebrow">Experience snapshot</p><h2>Business context first. Technology applied with intent.</h2></div><p>Experience across tourism operations, commercial marketing, hospitality performance analysis and enterprise software.</p></div><div className="shell compact-timeline">{experiences.slice(0, 5).map((item, index) => <article className="timeline-item" key={item.id || item.organisation}><div className="timeline-marker">0{index + 1}</div><div><p className="timeline-date">{item.dates}</p><h3>{item.role}</h3><p className="timeline-org">{item.organisation} · {item.location}</p><p>{item.summary}</p></div></article>)}</div><div className="shell timeline-action"><Link href="/experience" className="button button-secondary">View full experience <Icon name="arrow" /></Link></div></section>
    <section className="section section-soft"><div className="shell section-header split-heading"><div><p className="eyebrow">Capability map</p><h2>Business-minded analytical and technical skills.</h2></div><p>Tools and methods used to organise data, improve customer interactions and make business processes more repeatable.</p></div><div className="shell skills-grid">{skillClusters.map((cluster, index) => <article className="skill-cluster" key={cluster.id || cluster.title}><span className="cluster-index">0{index + 1}</span><h3>{cluster.title}</h3><div className="skill-tags">{cluster.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
    <section className="section education-section"><div className="shell education-grid"><div><p className="eyebrow">Education & certification</p><h2>Built on business intelligence, extending into data and e-commerce.</h2></div><div className="education-list">{education.map((item) => <article key={item.id || item.title}><h3>{item.title}</h3><p>{item.organisation}</p><span>{item.date}</span>{item.detail && <small>{item.detail}</small>}</article>)}{certifications.map((item) => <article className="cert-card" key={item.id || item.title}><p className="eyebrow">Certification</p><h3>{item.title}{item.issuer ? ` - ${item.issuer}` : ''}</h3>{item.detail && <small>{item.detail}</small>}</article>)}</div></div></section>
    <section className="section contact-cta-section"><div className="shell contact-cta"><p className="eyebrow">Let’s connect</p><h2>Open to connecting with professionals working in Marketing Analytics, Commercial Analytics, Business Intelligence, E-Commerce, Revenue Operations and Digital Growth.</h2><div className="hero-actions"><a className="button button-primary" href={profile.linkedIn} target="_blank" rel="noreferrer"><Icon name="linkedin" /> LinkedIn</a><a className="button button-secondary" href={`mailto:${profile.email}`}><Icon name="mail" /> Email Ahmed</a><Link className="text-link" href="/resume">Download CV <Icon name="download" /></Link></div></div></section>
  </>;
}
