import type { Metadata } from 'next';
import { PageHero } from '@/components/page-hero';
import { Icon } from '@/components/icons';
import { getPortfolioContent } from '@/lib/cms';

export const metadata: Metadata = { title: 'Resume / CV', description: 'Download CV versions tailored for European analytics roles, French-language applications, ATS systems and Canada-focused applications.', alternates: { canonical: '/resume' }, openGraph: { title: 'Resume / CV | Ahmed Aziz Mhiri', description: 'Choose the CV format that best fits the application context.' } };

export default async function ResumePage() {
  const { resumes } = await getPortfolioContent();
  return <><PageHero eyebrow="Resume / CV" title="CV formats for recruiters and application workflows." intro="Choose the version that best fits the role, language and screening process. The English professional CV is the best starting point for most European analytics opportunities." /><section className="section"><div className="shell resume-grid">{resumes.map((resume, index) => <article className="resume-card" key={resume.id || resume.title}><span className="resume-number">0{index + 1}</span><p className="project-industry">{resume.language} - {resume.use}</p><h2>{resume.title}</h2><p>{resume.description}</p><div className="resume-downloads"><a className="button button-primary" href={resume.pdf} download><Icon name="download" /> Download PDF <small>{resume.pdfSize}</small></a><a className="button button-secondary" href={resume.docx} download><Icon name="download" /> Download DOCX <small>{resume.docxSize}</small></a></div></article>)}</div></section><section className="section section-soft"><div className="shell content-narrow"><p className="eyebrow">Which version to choose</p><h2>Start with the English professional CV for recruiter screening.</h2><p>Use the ATS version for online forms, the French version for French-language applications, and the Canada-focused version only when the opportunity specifically asks for that market format.</p></div></section></>;
}